-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3BB3Xj55ZXQyvkL7
R/8qmrmyQOvX/dAj2NXHNfEZbkigCgYIKoZIzj0DAQehRANCAARrcWAXa66oiqgX
d+QM2w0ZHPw/UFTQ5DKvy0sEk1sFJ8aNztnShjNGqlR3lVRVzrfnEUh/YPKPWIX6
T7cR22hN
-----END PRIVATE KEY-----